name: jardaly
description: تطبيق جردلي - مساعد الذكي للمصاريف والمحاسبة

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  
  # UI dependencies
  fl_chart: ^1.0.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  animations: ^2.0.8
  animated_counter: ^1.0.0
  animated_text_kit: ^4.2.2
  iconsax: ^0.0.8
  flutter_local_notifications: ^16.3.0
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Local Storage
  hive_flutter: ^1.1.0
  
  # File handling
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  url_launcher: ^6.2.2
  
  # Localization
  flutter_localizations:
    sdk: flutter
  
  # Speech and ML
  speech_to_text: ^6.6.0
  google_mlkit_text_recognition: ^0.11.0
  
  # Database
  supabase_flutter: ^2.0.0
  
  # Social Authentication
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.3
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  dio: ^5.8.0+1
  webview_flutter: ^4.13.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/logo.png
    - assets/logo.svg
  
  # تم إزالة إعدادات الخطوط المؤقتة
  # يمكنك إضافة الخطوط لاحقاً بعد تنزيلها

